const express = require('express')
const cors = require('cors')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const app = express()
// app.use(morgan('combined'))
app.use(cors())
app.use(bodyParser.json())
app.post('/register',(req,res)=>{
    console.log(req.body.email)
    res.send(req.body.email)
})
console.log('server start')
app.listen(process.env.PORT||8000)