const express = require('express')
const cors = require('cors')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const app = express()
const sequelize = require('./models')
const config = require('./config/config')
// app.use(morgan('combined'))
app.use(cors())
app.use(bodyParser.json())
require(',/routes')(app)
console.log('server start')

sequelize.sync().then(()=>app.listen(config.port))
console.log('server started on port')
console.log(config.port)
app.listen(process.env.PORT||8000)